Resources:
  CognitoUserPool: #Store all user creadentials here
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: ${self:provider.stage}-tasks-api-pool
      AutoVerifiedAttributes:
        - email

  CognitoUserPoolClient: #For frontend authentication
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: ${self:provider.stage}-tasks-api-client
      UserPoolId:
        Ref: CognitoUserPool
      ExplicitAuthFlows:
        - ADMIN_NO_SRP_AUTH
      GenerateSecret: false

Outputs:
  UserPoolId:
    Value:
      Ref: CognitoUserPool

  UserPoolClientId:
    Value:
      Ref: CognitoUserPoolClient
