name: UI deploy
on:
  push:
    paths:
      - "services/tasks_ui/**"
      - ".github/workflows/ui.yml"

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1
  APP_ENVIRONMENT: development
  VITE_VUE_APP_API_URL: #Your api gateway url on aws

jobs:
  deploy-development:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [16]
    defaults:
      run:
        working-directory: services/tasks_ui
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install serverless
        run: npm install -g serverless
      - name: Install NPM dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Save credentials
        run: serverless config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}  -o
      - name: Deploy
        run: sls deploy --stage development --verbose
